### ISSUE TITLE
Expand Waste Database and Use Transfer Learning

### ISSUE THREAD

**Issue by sumn2u** [sumn2u/deep-waste-app#4]
# Problem
This project utilizes the [Trashnet](https://github.com/garythung/trashnet) dataset, comprising of 2527 images across six classes: glass, paper, cardboard, plastic, metal, and trash.

- 501 glass
- 594 paper
- 403 cardboard
- 482 plastic
- 410 metal
- 137 trash

Training an effective waste classification model requires more high-quality, diverse data.

# Actions 
 Create a separate waste dataset by collecting from different sources and use transfer learning approach to add new knowledge.
 
 # References
 - [Classification Model](https://colab.research.google.com/drive/1yWqc8TRS0I21RdfHLPRTQIs37ANOx-Uq)
 - [Dataset Analysis ](https://colab.research.google.com/drive/1JPwI75T_PMlTITO3tDmIhGEVsIREnGHa?usp=sharing#scrollTo=K1eylFsQ_58q)
 - [Research Paper](https://www.aimspress.com/article/doi/10.3934/ctr.2023008)
 - [Building Process](https://sumn2u.medium.com/deep-learning-approach-to-manage-household-waste-via-mobile-app-4186292b266b)

**Comment by sumn2u** [comment]
This [repo](https://github.com/AgaMiko/waste-datasets-review) reviews waste datasets.

**Comment by sumn2u** [comment]
[Update] The dataset is expanded [here](https://www.kaggle.com/datasets/sumn2u/garbage-classification-v2/).

**Comment by computer-404** [comment]
Added to the chain.

**Comment by sumn2u** [comment]
@computer-404 I applied transfer learning here. Let me know what you think of it? 

https://www.kaggle.com/code/sumn2u/garbage-classification-transfer-learning/

**Comment by sumn2u** [comment]
The new dataset underwent transfer learning methods, and its results are benchmarked [here](https://arxiv.org/abs/2402.09437).
